@echo off
rem NOTE: never name a variable LIB here - that is the linker's library search path.
call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
set HERE=%~dp0
rem Provenance musi opisywac DRZEWO, KTORE WLASNIE KOMPILUJEMY. Sciezka zapisana
rem na sztywno powodowala, ze build w czystym checkoucie stemplowal SHA i dirty
rem state zupelnie innego repozytorium - stempel wygladal poprawnie, a opisywal
rem co innego. Repo wyznaczamy z polozenia tego skryptu.
for %%I in ("%HERE%..\..") do set REPO=%%~fI
rem box3d.lib moze pochodzic z innego, zbudowanego drzewa - jej tozsamosc niesie
rem osobny stempel ponizej, wiec nie klamie o zrodle.
if "%JOZZ_BOX3D_LIB%"=="" (
	set BOX3DLIB=%REPO%\build\src\Release\box3d.lib
) else (
	set BOX3DLIB=%JOZZ_BOX3D_LIB%
)

rem --- provenance: an artifact that does not certify itself is not evidence ---
pushd "%REPO%"
for /f %%i in ('git rev-parse --short HEAD') do set SHA=%%i
for /f %%i in ('git status --porcelain -- src include ^| find /c /v ""') do set CORECHG=%%i
popd
set DIRTY=core clean
if not "%CORECHG%"=="0" set DIRTY=CORE MODIFIED - %CORECHG% files
set LIBSTAMP=MISSING
for %%F in ("%BOX3DLIB%") do set LIBSTAMP=%%~tF - %%~zF bytes

rem SHA-256 zrodla i biblioteki wpiekane w binarke: manifest Q2A ma niesc
rem tozsamosc tego, co faktycznie zostalo skompilowane i zlinkowane.
rem Uwaga: `set X=%%h & set Y=1` doklejalby spacje do wartosci hasha.
set SRCSHA=unknown
for /f "skip=1 tokens=1 delims= " %%h in ('certutil -hashfile "%HERE%wheel_bench.c" SHA256') do (
	if not defined SRCSHA_SET (
		set SRCSHA=%%h
		set SRCSHA_SET=1
	)
)
set LIBSHA=unknown
for /f "skip=1 tokens=1 delims= " %%h in ('certutil -hashfile "%BOX3DLIB%" SHA256') do (
	if not defined LIBSHA_SET (
		set LIBSHA=%%h
		set LIBSHA_SET=1
	)
)

> "%HERE%bench_provenance.h" echo // generated by build.bat - do not edit
>>"%HERE%bench_provenance.h" echo #define BENCH_GIT_SHA "%SHA%"
>>"%HERE%bench_provenance.h" echo #define BENCH_GIT_DIRTY "%DIRTY%"
>>"%HERE%bench_provenance.h" echo #define BENCH_LIB_STAMP "%LIBSTAMP%"
>>"%HERE%bench_provenance.h" echo #define BENCH_SRC_SHA256 "%SRCSHA%"
>>"%HERE%bench_provenance.h" echo #define BENCH_LIB_SHA256 "%LIBSHA%"

pushd "%HERE%"
cl /nologo /O2 /I "%REPO%\include" /I . wheel_bench.c /Fe:wheel_bench.exe /link "%BOX3DLIB%"
set RC=%ERRORLEVEL%
popd
exit /b %RC%
